# Generated by Django 4.2.5 on 2023-10-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_remove_settings_end_time_alter_settings_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='start_time',
            field=models.TimeField(verbose_name='время старта'),
        ),
    ]
