# Generated by Django 4.2.5 on 2023-12-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_maillog_message_maillog_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='start_time',
        ),
    ]
