# Generated by Django 4.2.5 on 2023-12-03 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_settings_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и время старта'),
        ),
    ]
